In [35]:
import pandas as ps

In [36]:
data = ps.read_csv("sec_bhavdata_full.csv")

In [37]:
data.head()

,SYMBOL,SERIES,DATE1,PREV_CLOSE,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,LAST_PRICE,CLOSE_PRICE,AVG_PRICE,TTL_TRD_QNTY,TURNOVER_LACS,NO_OF_TRADES,DELIV_QTY,DELIV_PER
0,20MICRONS,EQ,04-Apr-2018,49.90,50.10,52.30,49.0,49.5,49.3,50.98,193457,98.62,1874,87220,45.08
1,21STCENMGM,BE,04-Apr-2018,35.00,35.50,35.50,35.0,35.0,35.0,35.02,1487,0.52,8,-,-
2,3IINFOTECH,EQ,04-Apr-2018,5.15,5.15,5.30,5.0,5.1,5.1,5.14,3773118,193.91,1210,2113580,56.02
3,3MINDIA,EQ,04-Apr-2018,20111.30,20111.30,21000.05,19851.0,20131.0,20105.0,20530.85,3744,768.67,1062,2513,67.12
4,5PAISA,BE,04-Apr-2018,344.15,349.80,357.80,341.0,347.0,347.0,347.29,5110,17.75,57,-,-

In [38]:
temp = data.loc[:,['SYMBOL', 'SERIES', 'DATE1', 'OPEN_PRICE', 'CLOSE_PRICE']]

In [40]:
temp[temp['SERIES'] == 'EQ']

          SYMBOL SERIES        DATE1  OPEN_PRICE  CLOSE_PRICE
0      20MICRONS     EQ  04-Apr-2018       50.10        49.30
2     3IINFOTECH     EQ  04-Apr-2018        5.15         5.10
3        3MINDIA     EQ  04-Apr-2018    20111.30     20105.00
5        63MOONS     EQ  04-Apr-2018      101.00       101.05
6        8KMILES     EQ  04-Apr-2018      704.95       689.75
7       A2ZINFRA     EQ  04-Apr-2018       28.85        27.90
8     AARTIDRUGS     EQ  04-Apr-2018      540.80       543.80
9       AARTIIND     EQ  04-Apr-2018     1165.00      1154.60
10     AARVEEDEN     EQ  04-Apr-2018       46.45        44.20
12          ABAN     EQ  04-Apr-2018      163.70       159.65
13           ABB     EQ  04-Apr-2018     1294.90      1271.35
14    ABBOTINDIA     EQ  04-Apr-2018     5674.00      5624.50
15     ABCAPITAL     EQ  04-Apr-2018      152.90       151.70
16         ABFRL     EQ  04-Apr-2018      147.90       151.00
19           ACC     EQ  04-Apr-2018     1554.00      1530.00
20       ACCELYA     EQ  04-Apr-2018     1359.90      1341.90
22           ACE     EQ  04-Apr-2018      176.80       172.55
24      ADANIENT     EQ  04-Apr-2018      162.45       151.45
25    ADANIPORTS     EQ  04-Apr-2018      368.00       367.80
26    ADANIPOWER     EQ  04-Apr-2018       25.05        25.05
27    ADANITRANS     EQ  04-Apr-2018      192.50       182.80
28      ADFFOODS     EQ  04-Apr-2018      240.00       220.65
29       ADHUNIK     EQ  04-Apr-2018        3.90         3.90
31        ADLABS     EQ  04-Apr-2018       53.25        51.55
32      ADORWELD     EQ  04-Apr-2018      405.80       389.25
33          ADSL     EQ  04-Apr-2018       22.35        21.70
34    ADVANIHOTR     EQ  04-Apr-2018       56.50        56.00
35    ADVENZYMES     EQ  04-Apr-2018      239.00       233.75
36     AEGISCHEM     EQ  04-Apr-2018      266.75       256.60
37           AFL     EQ  04-Apr-2018       53.45        52.20
...          ...    ...          ...         ...          ...
1819  WEIZMANIND     EQ  04-Apr-2018       48.45        46.65
1820     WELCORP     EQ  04-Apr-2018      141.00       135.05
1821      WELENT     EQ  04-Apr-2018      153.95       147.95
1822      WELINV     EQ  04-Apr-2018      154.45       148.00
1823  WELSPUNIND     EQ  04-Apr-2018       58.45        57.80
1824       WENDT     EQ  04-Apr-2018     3138.00      3279.60
1825      WHEELS     EQ  04-Apr-2018     2248.15      2233.60
1826   WHIRLPOOL     EQ  04-Apr-2018     1534.90      1509.80
1828  WINDMACHIN     EQ  04-Apr-2018      105.35       102.60
1830       WIPRO     EQ  04-Apr-2018      285.00       281.60
1831  WOCKPHARMA     EQ  04-Apr-2018      775.00       755.80
1832    WONDERLA     EQ  04-Apr-2018      366.55       360.00
1834         WSI     EQ  04-Apr-2018        7.85         7.55
1835  WSTCSTPAPR     EQ  04-Apr-2018      261.90       255.10
1836   XCHANGING     EQ  04-Apr-2018       57.80        59.25
1837   XPROINDIA     EQ  04-Apr-2018       50.95        50.60
1838     YESBANK     EQ  04-Apr-2018      313.00       305.45
1839  ZANDUREALT     EQ  04-Apr-2018     1947.00      1956.40
1840        ZEEL     EQ  04-Apr-2018      585.95       574.45
1842    ZEELEARN     EQ  04-Apr-2018       36.95        36.75
1843    ZEEMEDIA     EQ  04-Apr-2018       39.90        39.10
1845  ZENITHEXPO     EQ  04-Apr-2018       49.00        46.10
1846  ZENSARTECH     EQ  04-Apr-2018      950.00       945.60
1847      ZENTEC     EQ  04-Apr-2018      120.50       116.85
1848       ZICOM     EQ  04-Apr-2018       16.40        19.50
1849  ZODIACLOTH     EQ  04-Apr-2018      173.40       169.35
1850   ZODJRDMKJ     EQ  04-Apr-2018       39.95        40.00
1852       ZUARI     EQ  04-Apr-2018      504.35       494.55
1853   ZUARIGLOB     EQ  04-Apr-2018      187.40       184.25
1854   ZYDUSWELL     EQ  04-Apr-2018     1239.85      1186.80

[1507 rows x 5 columns]